### PR TITLE
Migrate from deprecated ludeeus container

### PR DESCRIPTION
**Pull request by natekspencer**
Following the guidelines from https://github.com/ludeeus/container#deprecated
Addresses https://github.com/bretterer/home-assistant-rivian/issues/76

### CODE REVIEW

**Comment by bretterer** [comment]
Thank you!   Have you confirmed the devcontainer still builds?

**Comment by natekspencer** [comment]
Yes, though I'm only able to test with my machine. So it's worth checking out my branch and trying it yourself.

**Comment by tmack8001** [comment]
I was testing this morning, but ran out of time before work.

Will text more this weekend on both PRs

**Comment by tmack8001** [comment]
I'm guessing there is something not quite right in my local environment.

```
=> ERROR resolve image config for docker.io/docker/dockerfile:1.4        30.0s
------
 > resolve image config for docker.io/docker/dockerfile:1.4:
------
Dockerfile.extended:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1.4
   2 |     ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
   3 |     
--------------------
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: failed to do request: Head "https://registry-1.docker.io/v2/docker/dockerfile/manifests/1.4": dial tcp 18.215.138.58:443: i/o timeout
```

I keep getting this error and have restarted and cleared several different systems and caches, can't determine yet what might be causing this to happen, the old container runs fine for me though.

**Comment by natekspencer** [comment]
What kind of machine do you use? And what docker version do you have? Maybe something with that is causing it not to build.

**Comment by tmack8001** [comment]
🤷

**Comment by natekspencer** [comment]
I wonder if this is related: https://github.com/microsoft/vscode-remote-release/issues/6920

**Comment by tmack8001** [comment]
Weird thing is I've pre-pulled both images and still not able to get vscode to build the devcontainer. Strangely the existing devcontainer image pulls and builds fine in vscode 🤷 

Now that I have my local env working again, don't feel this is super high priority to fix... as I don't want to break things yet again for myself. Thanks for contributing this so far, wonder if there is some conflict unique to my environment.

**Comment by natekspencer** [comment]
Agreed, this one isn't super important yet.

**Review by bretterer — APPROVED** [review]
LGTM

**Pull request merged**
