### PR TITLE
Update various sensors (e.g., add icons, tweak friendly names, capitalize some states, etc.)

### PR DESCRIPTION
**Pull request by krazos**
Note that I have split this PR into multiple commits to make it easier to pick and choose which changes, if any, folks want to merge:

1. I have proposed icons for various sensors that did not already have them.  Please feel free to choose alternative icons, if others think there more appropriate options.  I also deleted the icon for the Gear Guard Alarm binary sensor.  The alarm clock did not seem like the most appropriate choice, and without a hardcoded icon, it will default to the customized on/off state-based icons for the `tamper` device class. 

2. I fixed a typo in the friendly name of Battery Thermal Runwaway Propagation sensor, and updated the friendly name of Gear Guard Video Terms Accepted to match the GraphQL name and avoid duplicating the name of the other Gear Guard Video Status sensor.  I also updated the key/entity_id for a few GraphQL sensors with underscores for consistency with HA entity_id convention.  Note this will orphan existing sensors and create new sensors in HA, requiring some clean up for existing users.

3. Various sensor values use inconsistent capitalization, space/underscore, etc.  I attempted to clean this up with some additional lambdas.

4. Previously, heated/ventilated seat binary sensors used HEAT/COLD device classes, which I thought were more intended to capture whether a given temperature sensor was above or below a threshold.  When off, the translated state shows as "Normal" in the UI, which looks odd.  I have proposed to change them to running device class, but I could also see removing the device class entirely and falling back to the standard "On/Off" binary sensor states.

### CODE REVIEW

**Comment by jrgutier** [comment]
Agree with the changes so far. I'd like to store the original returned value of the sensor as an attribute if changed, similar to what happens on the binary sensors.

**Comment by krazos** [comment]
Thanks. There may be a better way to add the native value attribute, but I've added a commit that should get the job done.

**Comment by krazos** [comment]
Totally happy if you all want to hold off on any or all of this.  Was just experimenting with incorporating some of the icons and  name/state processing tweaks that I've been using locally through entity customization, templates, etc.

**Comment by tmack8001** [comment]
rebased and added a few icons for seat heat/vent as well as steering wheel (too bad there isn't a heated-steering icon to use as well)

**Review by tmack8001 — APPROVED** [review]

**Comment by tmack8001** [comment]
LGTM and I tested locally, some sensors due to name changes duplicated (uninstall and reinstall should fix that)

**Review by bretterer — APPROVED** [review]

**Pull request merged**
