### PR TITLE
Add update entity for software ota

### PR DESCRIPTION
**Pull request by natekspencer**

### CODE REVIEW

**Comment by jrgutier** [comment]
> 

Hey Nate, what exactly does this do that querying the normal sensor doesn't? Just trying to understand the value add.

**Comment by natekspencer** [comment]
Not much right now, but it consolidates 3 other sensors into one as well as shows the progress and a notification within HA when there is an update. The idea, if you're open to it, is to deprecate the others so the information available is more relevant and less busy

**Comment by natekspencer** [comment]
Additionally, if control of the vehicle is figured out, including updating the software, this will prevent having to create a button entity or service to do so.

**Comment by natekspencer** [comment]
I also believe current/available version year/week/number/git hash could all be rolled into extra_state_attributes on this entity without losing any functionality and cleaning up the number of sensors displayed, essentially converting 11 current sensors to 1 update entity.

**Comment by tmack8001** [comment]
Think this is a fine addition to me. Basically consolidates what I've been doing in the dashboards to display "update available" automatically into a single native entity which contains that information as well as some secondary information.

Like it, though we may choose to leave the existing sensors as is or deprecate and eventually remove as not needed if we can extract from the attributes of this entity.

**Review by tmack8001 — APPROVED** [review]

**Comment by tmack8001** [comment]
image
image
image

@natekspencer maybe we should make the diagnostic state icon for this `mdi:package` and not the Rivian Compass Logo?

**Comment by natekspencer** [comment]
> Wish I tested this during and around the downloading/installation/preparing steps of the last OTA.

My last updates were specifically a result of testing against the latest OTA download, so it helped to refine it a bit.

**Comment by natekspencer** [comment]
> @natekspencer maybe we should make the diagnostic state icon for this `mdi:package` and not the Rivian Compass Logo?

This is the default HA functionality. I don't really have a preference either way.

**Comment by tmack8001** [comment]
Here is also a preview of the additional attributes stored on the entity 
image

should `current_version` not be `2023.10.1` and `available_version` is fine to leave blank always found the `0.0.0` to be an odd choice, but someone decided those fields should be non empty integer values 😆

**Comment by tmack8001** [comment]
> should `current_version`

forget me... can't think straight today (sick kiddo at home) this is a complex/json object containing other data.

**Comment by natekspencer** [comment]
> should `current_version` not be `2023.10.1` and `available_version` is fine to leave blank always found the `0.0.0` to be an odd choice, but someone decided those fields should be non empty integer values 😆

The state view of that makes it look weird. current_version and available_version are actually json
{{ state_attr('update.rivian_software_ota','current_version') }}

**Comment by tmack8001** [comment]
Ok neither do I, looks good to me.

**Comment by natekspencer** [comment]
Agreed the '0.0.0' is weird, haha

**Pull request merged**
