### PR TITLE
feat: add polling interval option and options flow.

### LINKED ISSUE #8: Allow customization of polling
Allow the user to specify the polling interval.  Possibly through configuration.yaml

```
rivian:
    polling: "P30S" //30 seconds in ISO8601 Duration format
```

### PR DESCRIPTION
**Pull request by STRML**
Fixes #8.

Modeled this off the HACS plugin for Tesla. Default polling interval is 11 minutes as is Tesla. I don't know if anyone knows the sleep internals of Rivians (they seem to be pretty braindead at the moment and vampire drain is very high). So I am guessing here. I certainly believe the old default of `5` is way too frequent.

As I'm new to HA I haven't figured out why the translations are not making their way into the "Configure"/Options menu. Perhaps you can help on that and merge. Thanks for your work on this plugin!

Screen Shot 2022-08-20 at 1 06 37 PM
Screen Shot 2022-08-20 at 1 08 49 PM

### CODE REVIEW

**Comment by jrgutier** [comment]
So, just FYI, we're querying the cloud, not the actual vehicle. So the only thing we hammer is Rivian's CDN. The vehicle phones home about every 30 seconds.

**Comment by STRML** [comment]
And that doesn't wake the car?

**Comment by bretterer** [comment]
@STRML as far as we can tell, it does not wake the car at all. Of course, there is no good way to actually test this, and there is very little information out there around this at the moment.

On the PR however, I appreciate the addition here and will take a look at it to see about getting it merged in.

**Comment by STRML** [comment]
At 660sec, this is my power state - considerably less clean than I'd think but doesn't seem to be affected by the polling. What does it look like for you at 5sec?

image

**Comment by jrgutier** [comment]
54C3472E-C695-44DB-9AEA-6502B8A65385
That’s mine. No changes.

**Comment by STRML** [comment]
Interesting. You actually have longer gaps between sleep cycles. I've attempted to turn off Gear Guard completely and turn off proximity lock/unlock to see if it would affect this (my vampire drain is pretty bad, approx 6-10mi/day). So far, no significant results.

I've identified four "power states" 

* Sleep (dark blue)
* Standby (orange, unclear what this is)
* Ready (purple)
* Go (light blue, driving)


Screen Shot 2022-08-22 at 12 09 54 PM

Any idea what "Standby" is? 

And how's your vampire drain? This is a day with Gear Guard on but the "away from home" setting toggled. 


Screen Shot 2022-08-22 at 12 11 23 PM
Screen Shot 2022-08-22 at 12 11 39 PM

**Comment by jrgutier** [comment]
I'll have to let you know later, I'm currently on a trip and it's plugged in at home. This has been the "drain"
C99A8054-CFB9-45B2-9295-8D38C54DCE3B_1_201_a

**Comment by STRML** [comment]
I can confirm from my own testing that turning polling off completely makes no difference to vampire drain. I still lose the same amount every day whether HA is on or off. 

We could put this on ice for now, but it may be something worth reviving if Rivian makes more strides toward eliminating vampire drain, and this actually *does* wake the vehicle too often.

For now, it seems it's always online, which is a practical problem that should be fixed.

**Comment by STRML** [comment]
With the latest update (2023.02) I am seeing as much as 6% drain with this integration on and less than 2% with it off. We should revive this.

**Comment by jrgutier** [comment]
Considering that the integration doesn't poll the vehicle directly... I have no clue what is causing this drain.

**Comment by tmack8001** [comment]
Here I'm adding for context I'm running the latest HA version and parked our truck at the train station (with gear guard on) and not plugged into a trickle charger (they were under construction).



We didn't see any severe drain and no more or less than we normally see, but it is interesting to view over the course of 5 days (just shy of a week).

**Comment by tmack8001** [comment]
With the migration to a graphql subscription in https://github.com/bretterer/home-assistant-rivian/pull/88 this becomes obsolete. Closing out. Thanks for the contribution.

**Pull request closed without merging**
