### PR TITLE
add history to attributes

### PR DESCRIPTION
**Pull request by jrgutier**
- add history so we can tell every possible value
- fix device_tracker occasionally going unavailable

### CODE REVIEW

**Review by tmack8001 — APPROVED** [review]
LGTM

**Comment by natekspencer** [comment]
> * add history so we can tell every possible value

@jrgutier Is this just displaying the previous value in `extra_state_attributes`?

**Review by bretterer — APPROVED** [review]
This looks great

**Comment by jrgutier** [comment]
Re: numerical, I wanted to see if the sensors ever returned anything that wasn't numerical. I can probably filter for it, but wanted to set this up for a wider net first. 

> NVM, I see this is really trying to track historical values to help facilitate decoding the Rivian API. This should probably exclude numerical sensors from history tracking which could quickly balloon the HA DB (e.g. battery will show all changes which isn't necessary `{68.900002, 69.200005, 69, 69.099998, 69.700005, 69.300003, 69.400002, 69.5, 69.599998, 69.800003, 69.900002, 70}`).

**Comment by natekspencer** [comment]
> Re: numerical, I wanted to see if the sensors ever returned anything that wasn't numerical. I can probably filter for it, but wanted to set this up for a wider net first.

Maybe for those fields then, you could exclude the numerical data from history logging? The __typename from the GraphQL query for those are TimeStampedFloat and TimeStampedInt so I'd be shocked if they came back differently, but weirder things have happened 🤣. That's probably why the available software versions come back as 0 instead of null now that I'm thinking about it.

**Comment by jrgutier** [comment]
> Maybe for those fields then, you could exclude the numerical data from history logging? The __typename from the GraphQL query for those are TimeStampedFloat and TimeStampedInt so I'd be shocked if they came back differently, but weirder things have happened 🤣. That's probably why the available software versions come back as 0 instead of null now that I'm thinking about it.

I went through and added this. The rivian-python-client needs to be modified to output __typename on sensors to work though.

**Pull request merged**
